[package]
name = "pi-image-builder-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.2.1"
loopdev = "0.4.0"
mbrman = "0.5.0"
reqwest = { version = "0.11.12", features = ["blocking"] }
sha256 = "1.1.1"
xz2 = "0.1.7"
